### ISSUE TITLE
This isn’t an issue but more a question

### ISSUE THREAD

**Issue by machinehistories** [adafruit/glider#21]
I was wondering if you’ve considered releasing this using the testflight service on ios. I got excited when I heard about the prospects of this app. It used to be there was a plethora or solutions to code microcontrollers on ios. One of my favortires was the lightblue bean loader. It was a remarkbly well developed ide that offered code completion, examples, and ota firware loading for cloud compiled arduino cpp. I have yet to see a tool as resolved on ios. I have seen several ios arduino solutions fall by the wayside and there is a vacuum. Currently I feel the best option is using espruino running in the ios web ble app. It would be great to see glider provide a much needed app solution that actually provides a robust contemporary solution. I really enjoy using the ipad to do some coding and it would be cool to take advantage of all the innovative adafruit hardware while working on an ipad. I know you can manually load a .py file off of a circuit python board and copy and paste edits but it just isn’t a slick solution. It’s a welcome work around but there neeeds to be a purpose built app along the same lines as what the bluefruit app did for ble. Maybe by offering glider on testflight you could speed up the development of this app.

**Comment by tannewt** [comment]
I'm glad you are excited about it! I'm hoping to get the pre-requisite BLE changes into CircuitPython in the first half of this year. The iOS app side of development is a separate large task that may take more time though. My hope is that by having CircuitPython support we can start having multiple apps support it.
