### ISSUE TITLE
errors when editing code on android

### ISSUE THREAD

**Issue by stellaw1** [adafruit/glider#4]
Glider runs and connects to circuit playground bluefruit fine, however, whenever an attempt is made to edit code on glider, errors appear. 

1) Variable `performance` can't be found in [code_editor.js](https://github.com/adafruit/glider/blob/a799ef025f42ae64a36314d2166c5a194581bd85/code-editor.js#L28)
![image](https://user-images.githubusercontent.com/46392676/86502649-5f316380-bd5a-11ea-8ee2-26903a9c1992.png)

2) When the above [line of code in code_editor.js](https://github.com/adafruit/glider/blob/a799ef025f42ae64a36314d2166c5a194581bd85/code-editor.js#L28) is commented out, an error stating changeCode is not a function appears. 
![image](https://user-images.githubusercontent.com/46392676/86502603-dfa39480-bd59-11ea-8e3a-0c1d19dec670.png)

**Comment by stellaw1** [comment]
I am currently researching into useReducer React Hook to find a solution for issue 2)

**Comment by tannewt** [comment]
I would ignore 1 since it's just a console.log line. The `patch` functionality was the last thing I was working on and would like to remove. It was meant to send a minimal diff over the BLE connection to modify the file but it's way more complicated than just sending the full file again.

**Comment by kpolnitz** [comment]
I'm getting a slightly different error after trying to edit the code.py file: 
![image](https://user-images.githubusercontent.com/20099584/88328036-b339c300-ccdc-11ea-9a47-d9fe78d9f10d.png)

**Comment by stellaw1** [comment]
solution to this error: https://stackoverflow.com/questions/55868484/referenceerror-cant-find-variable-textencoder

> I'm getting a slightly different error after trying to edit the code.py file:
> ![image](https://user-images.githubusercontent.com/20099584/88328036-b339c300-ccdc-11ea-9a47-d9fe78d9f10d.png)

**Comment by stellaw1** [comment]
https://github.com/adafruit/glider/pull/12
